# Generated by Django 5.2 on 2025-04-30 21:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductPrompt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "product_title",
                    models.CharField(help_text="Title of the product", max_length=255),
                ),
                (
                    "product_description",
                    models.TextField(
                        help_text="Description of the product used for prompt generation"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the user who requested the prompt",
                        max_length=254,
                    ),
                ),
                (
                    "prompt_text",
                    models.TextField(help_text="The generated prompt text"),
                ),
                (
                    "model_used",
                    models.CharField(
                        help_text="AI model used for generation", max_length=100
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this prompt has been approved for use",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Optional product category to help with prompt optimization",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to the Celery task that generated this prompt",
                        max_length=255,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Prompt",
                "verbose_name_plural": "Product Prompts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product_title"], name="core_produc_product_13385c_idx"
                    ),
                    models.Index(fields=["email"], name="core_produc_email_5469ef_idx"),
                    models.Index(
                        fields=["created_at"], name="core_produc_created_68e7ba_idx"
                    ),
                    models.Index(
                        fields=["category"], name="core_produc_categor_e151e8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoGeneration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Email of the user who requested the video",
                        max_length=254,
                    ),
                ),
                (
                    "product_title",
                    models.CharField(help_text="Title of the product", max_length=255),
                ),
                (
                    "product_description",
                    models.TextField(help_text="Description of the product"),
                ),
                (
                    "input_image_url",
                    models.URLField(help_text="URL to the uploaded product image"),
                ),
                (
                    "output_video_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to the generated video (when complete)",
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current status of the video generation",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "task_id",
                    models.CharField(
                        blank=True,
                        help_text="Reference to the Celery task",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if the generation failed",
                        null=True,
                    ),
                ),
                (
                    "prompt",
                    models.ForeignKey(
                        blank=True,
                        help_text="The prompt used for this video generation",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_generations",
                        to="core.productprompt",
                    ),
                ),
            ],
            options={
                "verbose_name": "Video Generation",
                "verbose_name_plural": "Video Generations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["email"], name="core_videog_email_69ba69_idx"),
                    models.Index(
                        fields=["status"], name="core_videog_status_57f7d3_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="core_videog_created_a87759_idx"
                    ),
                ],
            },
        ),
    ]
