# Generated by Django 5.2 on 2025-05-03 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IPUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True,
                        help_text="The IP address of the user.",
                        unique=True,
                    ),
                ),
                (
                    "free_generations_used",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of free videos generated by this IP.",
                    ),
                ),
                (
                    "last_used_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Timestamp of the last generation attempt by this IP.",
                    ),
                ),
            ],
            options={
                "verbose_name": "IP Usage",
                "verbose_name_plural": "IP Usages",
                "ordering": ["-last_used_at"],
            },
        ),
    ]
